name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 12 * * 3' 
    - cron: '0 22 * * 5' 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  
        java: [11, 13, 17]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Set up JDK ${{ matrix.java }} 
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 
        with:
          arguments: build

