name: Java CI with Gradle
on:
  schedule:
    - cron: '30 12 * * 3'  
    - cron: '0 22 * * 5'   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java-version: [11, 13, 17]  
        platform: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: JDK 17
          distribution: 'temurin'
      - name: Make Gradlew executable1
        if: ${{ matrix.platform == 'ubuntu-latest' || matrix.platform == 'macOS-latest' }}
        run: chmod +x gradlew
      - name: Make Gradlew executable2
        if: ${{ matrix.platform == 'windows-latest'}}
        run: giveperm [gradlew.bat]
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 
        with:
          arguments: build
