name: Scheduled Builds

on:
  schedule:
    - cron: '30 12 * * 3'  # Запуск каждую среду в 12:30
    - cron: '0 22 * * 5'   # Запуск каждую пятницу в 22:00

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java-version: [11, 13, 17]  # Можно добавить другие версии, если необходимо
        platform: [ubuntu-latest, windows-latest, macOS-latest]  # Можно добавить другие платформы, если необходимо

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Gradle
        run: ./gradlew build  # Или команда для сборки проекта с использованием Gradle
        
      - name: Run Tests
        run: ./gradlew test  # Или команда для запуска тестов
